// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/get_user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/get_user_usecase.go -destination=internal/mocks/mock_get_user_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserUseCase is a mock of GetUserUseCase interface.
type MockGetUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserUseCaseMockRecorder
	isgomock struct{}
}

// MockGetUserUseCaseMockRecorder is the mock recorder for MockGetUserUseCase.
type MockGetUserUseCaseMockRecorder struct {
	mock *MockGetUserUseCase
}

// NewMockGetUserUseCase creates a new mock instance.
func NewMockGetUserUseCase(ctrl *gomock.Controller) *MockGetUserUseCase {
	mock := &MockGetUserUseCase{ctrl: ctrl}
	mock.recorder = &MockGetUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserUseCase) EXPECT() *MockGetUserUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetUserUseCase) Exec(user entities.User) (entities.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", user)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exec indicates an expected call of Exec.
func (mr *MockGetUserUseCaseMockRecorder) Exec(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetUserUseCase)(nil).Exec), user)
}
