// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/create_notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/create_notification_usecase.go -destination=internal/mocks/mock_create_notification_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateNotificationUseCase is a mock of CreateNotificationUseCase interface.
type MockCreateNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateNotificationUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateNotificationUseCaseMockRecorder is the mock recorder for MockCreateNotificationUseCase.
type MockCreateNotificationUseCaseMockRecorder struct {
	mock *MockCreateNotificationUseCase
}

// NewMockCreateNotificationUseCase creates a new mock instance.
func NewMockCreateNotificationUseCase(ctrl *gomock.Controller) *MockCreateNotificationUseCase {
	mock := &MockCreateNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateNotificationUseCase) EXPECT() *MockCreateNotificationUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockCreateNotificationUseCase) Exec(userID uint, userEmail string, notification entities.Notification) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", userID, userEmail, notification)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockCreateNotificationUseCaseMockRecorder) Exec(userID, userEmail, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockCreateNotificationUseCase)(nil).Exec), userID, userEmail, notification)
}
