// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/jwt_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/jwt_service.go -destination=internal/mocks/mock_jwt_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockJwTokenService is a mock of JwTokenService interface.
type MockJwTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockJwTokenServiceMockRecorder
	isgomock struct{}
}

// MockJwTokenServiceMockRecorder is the mock recorder for MockJwTokenService.
type MockJwTokenServiceMockRecorder struct {
	mock *MockJwTokenService
}

// NewMockJwTokenService creates a new mock instance.
func NewMockJwTokenService(ctrl *gomock.Controller) *MockJwTokenService {
	mock := &MockJwTokenService{ctrl: ctrl}
	mock.recorder = &MockJwTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwTokenService) EXPECT() *MockJwTokenServiceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJwTokenService) GenerateToken(email string, id uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", email, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJwTokenServiceMockRecorder) GenerateToken(email, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwTokenService)(nil).GenerateToken), email, id)
}

// ValidateToken mocks base method.
func (m *MockJwTokenService) ValidateToken(tokenString string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJwTokenServiceMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJwTokenService)(nil).ValidateToken), tokenString)
}
