// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/simulated_api_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/simulated_api_service.go -destination=internal/mocks/mock_simulated_api_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSimulatedApiService is a mock of SimulatedApiService interface.
type MockSimulatedApiService struct {
	ctrl     *gomock.Controller
	recorder *MockSimulatedApiServiceMockRecorder
	isgomock struct{}
}

// MockSimulatedApiServiceMockRecorder is the mock recorder for MockSimulatedApiService.
type MockSimulatedApiServiceMockRecorder struct {
	mock *MockSimulatedApiService
}

// NewMockSimulatedApiService creates a new mock instance.
func NewMockSimulatedApiService(ctrl *gomock.Controller) *MockSimulatedApiService {
	mock := &MockSimulatedApiService{ctrl: ctrl}
	mock.recorder = &MockSimulatedApiServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimulatedApiService) EXPECT() *MockSimulatedApiServiceMockRecorder {
	return m.recorder
}

// RandomizeHTTPStatus mocks base method.
func (m *MockSimulatedApiService) RandomizeHTTPStatus() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomizeHTTPStatus")
	ret0, _ := ret[0].(int)
	return ret0
}

// RandomizeHTTPStatus indicates an expected call of RandomizeHTTPStatus.
func (mr *MockSimulatedApiServiceMockRecorder) RandomizeHTTPStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomizeHTTPStatus", reflect.TypeOf((*MockSimulatedApiService)(nil).RandomizeHTTPStatus))
}
