// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/update_user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/update_user_usecase.go -destination=internal/mocks/mock_update_user_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateUserUseCase is a mock of UpdateUserUseCase interface.
type MockUpdateUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateUserUseCaseMockRecorder is the mock recorder for MockUpdateUserUseCase.
type MockUpdateUserUseCaseMockRecorder struct {
	mock *MockUpdateUserUseCase
}

// NewMockUpdateUserUseCase creates a new mock instance.
func NewMockUpdateUserUseCase(ctrl *gomock.Controller) *MockUpdateUserUseCase {
	mock := &MockUpdateUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserUseCase) EXPECT() *MockUpdateUserUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockUpdateUserUseCase) Exec(userEmail string, user entities.User) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", userEmail, user)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockUpdateUserUseCaseMockRecorder) Exec(userEmail, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockUpdateUserUseCase)(nil).Exec), userEmail, user)
}
