// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/update_notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/update_notification_usecase.go -destination=internal/mocks/mock_update_notification_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateNotificationUseCase is a mock of UpdateNotificationUseCase interface.
type MockUpdateNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateNotificationUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateNotificationUseCaseMockRecorder is the mock recorder for MockUpdateNotificationUseCase.
type MockUpdateNotificationUseCaseMockRecorder struct {
	mock *MockUpdateNotificationUseCase
}

// NewMockUpdateNotificationUseCase creates a new mock instance.
func NewMockUpdateNotificationUseCase(ctrl *gomock.Controller) *MockUpdateNotificationUseCase {
	mock := &MockUpdateNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateNotificationUseCase) EXPECT() *MockUpdateNotificationUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockUpdateNotificationUseCase) Exec(userID uint, notificationID int, notification entities.Notification) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", userID, notificationID, notification)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockUpdateNotificationUseCaseMockRecorder) Exec(userID, notificationID, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockUpdateNotificationUseCase)(nil).Exec), userID, notificationID, notification)
}
