// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/notification_repository.go -destination=internal/mocks/mock_notification_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockNotificationRepository) CreateNotification(arg0 uint, arg1 entities.Notification) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", arg0, arg1)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotification), arg0, arg1)
}

// DeleteNotificationByID mocks base method.
func (m *MockNotificationRepository) DeleteNotificationByID(notificationID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotificationByID", notificationID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNotificationByID indicates an expected call of DeleteNotificationByID.
func (mr *MockNotificationRepositoryMockRecorder) DeleteNotificationByID(notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotificationByID", reflect.TypeOf((*MockNotificationRepository)(nil).DeleteNotificationByID), notificationID)
}

// DoesNotificationExistsAndBelongsToUser mocks base method.
func (m *MockNotificationRepository) DoesNotificationExistsAndBelongsToUser(arg0, arg1 uint) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesNotificationExistsAndBelongsToUser", arg0, arg1)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoesNotificationExistsAndBelongsToUser indicates an expected call of DoesNotificationExistsAndBelongsToUser.
func (mr *MockNotificationRepositoryMockRecorder) DoesNotificationExistsAndBelongsToUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesNotificationExistsAndBelongsToUser", reflect.TypeOf((*MockNotificationRepository)(nil).DoesNotificationExistsAndBelongsToUser), arg0, arg1)
}

// GetNotificationsByUser mocks base method.
func (m *MockNotificationRepository) GetNotificationsByUser(arg0 uint) ([]entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationsByUser", arg0)
	ret0, _ := ret[0].([]entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationsByUser indicates an expected call of GetNotificationsByUser.
func (mr *MockNotificationRepositoryMockRecorder) GetNotificationsByUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationsByUser", reflect.TypeOf((*MockNotificationRepository)(nil).GetNotificationsByUser), arg0)
}

// SetSentAt mocks base method.
func (m *MockNotificationRepository) SetSentAt(arg0 entities.Notification, arg1 time.Time) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSentAt", arg0, arg1)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSentAt indicates an expected call of SetSentAt.
func (mr *MockNotificationRepositoryMockRecorder) SetSentAt(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSentAt", reflect.TypeOf((*MockNotificationRepository)(nil).SetSentAt), arg0, arg1)
}

// UpdateNotification mocks base method.
func (m *MockNotificationRepository) UpdateNotification(notification entities.Notification) (entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotification", notification)
	ret0, _ := ret[0].(entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotification indicates an expected call of UpdateNotification.
func (mr *MockNotificationRepositoryMockRecorder) UpdateNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotification", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateNotification), notification)
}
