// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/get_notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/get_notification_usecase.go -destination=internal/mocks/mock_get_notification_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockGetNotificationsByUserUseCase is a mock of GetNotificationsByUserUseCase interface.
type MockGetNotificationsByUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetNotificationsByUserUseCaseMockRecorder
	isgomock struct{}
}

// MockGetNotificationsByUserUseCaseMockRecorder is the mock recorder for MockGetNotificationsByUserUseCase.
type MockGetNotificationsByUserUseCaseMockRecorder struct {
	mock *MockGetNotificationsByUserUseCase
}

// NewMockGetNotificationsByUserUseCase creates a new mock instance.
func NewMockGetNotificationsByUserUseCase(ctrl *gomock.Controller) *MockGetNotificationsByUserUseCase {
	mock := &MockGetNotificationsByUserUseCase{ctrl: ctrl}
	mock.recorder = &MockGetNotificationsByUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetNotificationsByUserUseCase) EXPECT() *MockGetNotificationsByUserUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetNotificationsByUserUseCase) Exec(userID uint) ([]entities.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", userID)
	ret0, _ := ret[0].([]entities.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetNotificationsByUserUseCaseMockRecorder) Exec(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetNotificationsByUserUseCase)(nil).Exec), userID)
}
