// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/delete_notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/delete_notification_usecase.go -destination=internal/mocks/mock_delete_notification_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteNotificationUseCase is a mock of DeleteNotificationUseCase interface.
type MockDeleteNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteNotificationUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteNotificationUseCaseMockRecorder is the mock recorder for MockDeleteNotificationUseCase.
type MockDeleteNotificationUseCaseMockRecorder struct {
	mock *MockDeleteNotificationUseCase
}

// NewMockDeleteNotificationUseCase creates a new mock instance.
func NewMockDeleteNotificationUseCase(ctrl *gomock.Controller) *MockDeleteNotificationUseCase {
	mock := &MockDeleteNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteNotificationUseCase) EXPECT() *MockDeleteNotificationUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockDeleteNotificationUseCase) Exec(userID, notificationID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", userID, notificationID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDeleteNotificationUseCaseMockRecorder) Exec(userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDeleteNotificationUseCase)(nil).Exec), userID, notificationID)
}
