// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/create_user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/create_user_usecase.go -destination=internal/mocks/mock_create_user_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/imakheri/notifications-thch/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUserUseCase is a mock of CreateUserUseCase interface.
type MockCreateUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateUserUseCaseMockRecorder is the mock recorder for MockCreateUserUseCase.
type MockCreateUserUseCaseMockRecorder struct {
	mock *MockCreateUserUseCase
}

// NewMockCreateUserUseCase creates a new mock instance.
func NewMockCreateUserUseCase(ctrl *gomock.Controller) *MockCreateUserUseCase {
	mock := &MockCreateUserUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserUseCase) EXPECT() *MockCreateUserUseCaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockCreateUserUseCase) Exec(user entities.User) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", user)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockCreateUserUseCaseMockRecorder) Exec(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockCreateUserUseCase)(nil).Exec), user)
}
