services:
 mysql-test:
  image: mysql:8.0
  container_name: mysql_test_db
  environment:
   MYSQL_ROOT_PASSWORD: root_password
   MYSQL_DATABASE: db_test_notification_manager
  ports:
    - "3307:3306"
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
   timeout: 20s
   retries: 10