version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/go:1.25.0
        environment:
          DB_NAME: notification_manager_test_db
          DB_USER: root
          DB_PASSWORD: root_password
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
      - image: mysql:8.0
        environment:
          MYSQL_DATABASE: notification_manager_test_db
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_TCP_PORT: 3307
    steps:
      - checkout
      - run:
          name: Setup Database
          command: |
            until nc -z 127.0.0.1 3307; do echo "Esperando MySQL..."; sleep 2; done
            go run cmd/db/main.go -all
      - run:
          name: Run Tests with gotestsum
          command: |
            mkdir -p ./test-results
            gotestsum --junitfile ./test-results/junit.xml ./...
      - store_test_results:
          path: ./test-results

workflows:
  main:
    jobs:
      - build_and_test